from version import VERSION

text = (
    f"""
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "iso2fpa"
#define MyAppVersion "{VERSION}"
#define MyAppPublisher "Ted Lazaros"
#define MyAppURL "https://tedlaz.github.io/weblinks"
#define MyAppExeName "iso2fpa.exe"
"""

    """
[Setup]
AppId={{A51583EE-7D3B-4D10-87ED-80E5CC49A249}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={%USERPROFILE}\\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=admin
OutputDir=.
OutputBaseFilename=setup_iso2fpa.{#MyAppVersion}
SetupIconFile=.\\iso2fpa-setup.ico
UninstallDisplayIcon={app}\\{#MyAppExeName}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "greek"; MessagesFile: "Greek.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: .\\FiraCode-Retina.ttf; DestDir: "{autofonts}"; FontInstall: "Fira Code Retina"; Flags: onlyifdoesntexist uninsneveruninstall
Source: .\\{#MyAppExeName}; DestDir: "{app}"; Flags: ignoreversion
Source: .\\dxaramidopoylosslibieratosepe; DestDir: "{app}"; Flags: ignoreversion
Source: .\\samarasisiaoe; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\\{#MyAppName}"; Filename: "{app}\\{#MyAppExeName}"
Name: "{autodesktop}\\{#MyAppName}"; Filename: "{app}\\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: "{app}\\fpagui.ini"
"""
)

if __name__ == '__main__':
    with open('installer.iss', 'w') as f:
        f.write(text)
